### ISSUE TITLE
Nested ParameterizedTypes throws a ClassCastException

### ISSUE THREAD

**Issue by robert-bor** [42BV/beanmapper#118]
When a property has nested ParameterizedType instances, a ClassCastException is thrown:

```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
```

This happens for example with this construction:
```
public List<List<String>> names;
```

The reason for this happening is that the single generic in the list of generics in the ParameterizedType contains another ParameterizedType. This instance cannot be cast to a class, but must have its ```rawType``` extracted to see its Class.

**Comment by marcus-talbot42** [comment]
Fixed by #119
