### ISSUE TITLE
Mapping an Enum field to an Enum field of the same type fails when a custom toString method is present. 

### ISSUE THREAD

**Issue by ctrl-alt-dev** [42BV/beanmapper#121]
I'm upgrading the beanmapper-spring-boot-starter from 0.1.0 to 3.0.1, which upgrades beanmapper from 0.1.8 to 3.0.1

I have an enum with a custom `toString()` implementation. 

Mapping the enum to a field of the same type with beanmapper fails with:

```
java.lang.IllegalArgumentException: No enum constant nl.ctrlaltdev.atlasscan.domain.user.UpdatePeriod.weekly
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_181]
	at io.beanmapper.core.converter.impl.AnyToEnumConverter.valueOf(AnyToEnumConverter.java:46) ~[beanmapper-3.0.1.jar:na]
```

The actual name of the Enum value is `WEEKLY`, not `weekly`.

When I looked at the `AnyToEnumConverter` it uses `source.toString()` as the lookup value for the enum. Which is a logical solution if your source object is any object but an enum.

In case of an enum I would expect it to use its `source.name()` which according to the Javadoc
> Returns the name of this enum constant, *exactly as declared* in its enum declaration.

Perhaps an `EnumToEnumConverter` can be introduced, or simply an additional check if the source type is an enum in the existing converter.

**Comment by marcus-talbot42** [comment]
Fixed by #148
