### ISSUE TITLE
@BeanStore

### ISSUE THREAD

**Issue by Rickvanderwaal** [42BV/beanmapper#33]
There should be a BeanStore annotation.
With BeanStore you can store a value. You can use this value in BeanConstruct, BeanProperty or in other annotations.
There should be a @ TempBeanStore  and a @ FixedBeanStore annotation. 
With the Temp annotation the value is only available for current mapping. 
With the Fixed annotation the Value is available always, also during other mappings.

**Comment by robert-bor** [comment]
Replaced with @BeanAlias
