### ISSUE TITLE
Enum innerclass is not mapped

### ISSUE THREAD

**Issue by jeroenvs** [42BV/beanmapper#38]
When I have an innerclass enumeration:

[code]
Roster {
 enum Frequency { ANNUAL, SEMESTER }
 private Frequency frequency;
}

RosterForm {
 private Roster.Frequency frequency;
}
[code]

The beanmapper first throws an ArrayIndexOutOfBoundsException in the bean unproxy. Then after fixing that the property is not mapped at all.

**Comment by Rickvanderwaal** [comment]
In de beanMapper kan als configuratie: beanMapper.addProxySkipClass(Enum.class); toegevoegd worden.
We gaan overwegen om dit standaard in de BeanMapper te zetten.
