### ISSUE TITLE
Enforce @BeanCollection notation on collections in compile time or generate a warning in runtime

### ISSUE THREAD

**Issue by bollebeer** [42BV/beanmapper#55]
Given the following correct example:
@BeanCollection(elementType = Result.class)
public List<Result> resultList;

At the moment the beanMapper does not enforce the elementType on collections at compile time neither generates a warning at runtime. Therefore debugging problems related to this missing annotation can take allot of time.

**Comment by Rickvanderwaal** [comment]
BeanCollection notation is not required on every field of type collection.
For example if you want to map a target collection which has the same type as the source collection.

**Comment by Rickvanderwaal** [comment]
Close for now. Feel free to reopen this issue if you have similar problems.
