### ISSUE TITLE
mapDebug to view BeanMapper mapping intent

### ISSUE THREAD

**Issue by robert-bor** [42BV/beanmapper#61]
In practice it is not always clear what plan BeanMapper is using to perform the mapping from one class to another.

It would be extremely useful to have a ```mapDebug``` method which works in the same way as the map method. 

Note that the easiest way to proceed would be to only have a mapDebug(Object source) method, and use the configuration parameters as provided by BeanMapperBuilder to add target instance (or target class) and possibly a target collection class.

Ideally, the plan used to perform the mapping is the same plan communicated to the caller of mapDebug. However, this would entail considerable refactoring effort.

The function returns the plan, which effectively means the source and target trees are shown next to each other. BeanMapper should convey which BeanConverter (if any) it will use for the mapping from a source to a target field. Also, if a field is of a type which is part of the base model package (important, because only these classes are considered for deep copying), it must be able to communicate this as well.

**Comment by ctrl-alt-dev** [comment]
Probably the easiest way of showing what BeanMapper is doing is using some well placed log statements. I've implemented this in a separate branch (61-log-based-debug). It outputs something like this:
```
SourceWithDate.sameType -> 
    TargetWithDateTime.sameType
TargetWithDateTime.diffType -> 
    LocalDateTimeToLocalDate -> 
    SourceWithDate.diffType
```   
It shows the source type and field, optionally the converter, and the target type and field.

The disadvantage to this approach is that there is now a slf4j Logger dependency in the codebase..
