### ISSUE TITLE
Getters and Setters

### ISSUE THREAD

**Issue by kevin93w** [42BV/beanmapper#8]
At this time, the bean mapper uses the private fields of the model. This should be changed so the bean mapper first checks availability for getters and setters, if not it searches for public fields and else it should throw an BeanNoPropertyException.

**Comment by jeroenvs** [comment]
+1

Created a testing branch for this case (feature/map-proxy).
I need this for a JIRA plugin where we map ActiveObject interfaces into a domain model. The interfaces have no actual fields, just getters and setters.

**Comment by jeroenvs** [comment]
Resolved in latest commit
