### ISSUE TITLE
The name field from an enum is not mapped to target field

### ISSUE THREAD

**Issue by sptdevos** [42BV/beanmapper#83]
When beanmapper tries to map a field from the source's superclass to a field of the target with the same fieldname a strict mapping exception is thrown.
When strict mapping is turned off, the field is not mapped; the target field remains null.

Test code (UserRole is an enum and RoleResult is a class with public 'name' field):
```java
    @Test
    public void beanMapper_shouldMapFieldsFromSuperclass() {
        BeanMapper beanMapper = new BeanMapperBuilder().build();
        RoleResult result = beanMapper.map(UserRole.ADMIN, RoleResult.class);
        Assert.assertEquals(UserRole.ADMIN.name(), result.name);
    }
```
Results in a BeanStrictMappingRequirementsException.
```java
    @Test
    public void beanMapper_shouldMapFieldsFromSuperclass() {
        BeanMapper beanMapper = new BeanMapperBuilder().setApplyStrictMappingConvention(false).build();
        RoleResult result = beanMapper.map(UserRole.ADMIN, RoleResult.class);
        Assert.assertEquals(UserRole.ADMIN.name(), result.name);
    }
```
Results in an assertion failure.

**Comment by robert-bor** [comment]
The ```BeanMatch``` has different results for v0.1.0 and v2.0.2

v0.1.0
<img width="550" alt="screen shot 2017-10-24 at 21 41 51" src="https://user-images.githubusercontent.com/813749/31964726-41350ad2-b905-11e7-959f-357ad30f0d68.png">

v2.0.2
<img width="360" alt="screen shot 2017-10-24 at 21 48 45" src="https://user-images.githubusercontent.com/813749/31964737-49c0cd58-b905-11e7-8b76-987bc740d68b.png">

**Comment by robert-bor** [comment]
It is indeed as I said, a side-effect of restricting the properties (ie, public fields and getters for source > targets).

<img width="472" alt="screen shot 2017-10-24 at 21 59 41" src="https://user-images.githubusercontent.com/813749/31965238-f7a7a4e0-b906-11e7-95c2-9f24a971d76d.png">

**Comment by robert-bor** [comment]
Root cause: the name property is private final in enum (modifier number 18). In v2 there is neither a public name field, not a public getter (ie, getName). Therefore the property is not available for reading. 

One solution could be to make an exception for the name property in an enum. What do you think @sptdevos ?

**Comment by robert-bor** [comment]
FieldPropertyAccessor:

Instead of:
```
    @Override
    public boolean isReadable() {
        return Modifier.isPublic(field.getModifiers());
    }
```

Will become:
```
    @Override
    public boolean isReadable() {
        return nameOfEnum() || Modifier.isPublic(field.getModifiers());
    }

    private boolean nameOfEnum() {
        return "name".equals(field.getName()) && field.getDeclaringClass().equals(Enum.class);
    }
```
